### PR TITLE
Add env files for each environment

### PR DESCRIPTION
**Pull request by carvil**

### CODE REVIEW

**Comment by alecgibson** [comment]
What will this be used for? We don't really have a notion of int/staging/prod on the prototype, do we? (Apart from maybe PR deployments). Is this for switching the environment we display on the actual prototype?

**Comment by carvil** [comment]
@alecgibson this is so we can point to a different environment in order to get data. I've done a demo on the Show and Tell about this and I think is quite useful for when we need to fetch different datasets. Does that make sense?

**Comment by alecgibson** [comment]
Makes sense. Is the actual environment set somewhere in Heroku, then? Also, does this mean that if we run the prototype locally it'll try to run against a local content store/static/etc?

**Comment by carvil** [comment]
Even though `dotenv` has a mechanism to switch between environments, I didn't use that because we don't necessarily want to tie in the rails environment with the  `.env` file for flexibility. Right now, we need to copy the file we want into the `.env` file and restart the server. The default env variables in `.env` right now are the production ones.

**Comment by alecgibson** [comment]
Riiight. So these files are "dummy" files that just get copy-pasted over `.env`? Rather than using `Dotenv.load`? A bit confusing - is it documented anywhere?

**Comment by carvil** [comment]
@alecgibson I've updated the README with instructions on how to use the different `.env` files.

**Review by alecgibson — APPROVED** [review]

**Pull request merged**
